name: win95_launcher
description: "An android home launcher in the style of windows 95"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '^3.10.4'
  flutter: '>=3.18.0'


dependencies:
  flutter:
    sdk: flutter

  android_intent_plus: ^6.0.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4

  flutter95: ^1.3.1
  flutter_device_apps: ^0.4.0
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: W95FA
      fonts:
        - asset: assets/fonts/W95FA.otf